import { KyselyDB, KyselyTransaction } from "../../database/types/kysely.types";
import { InsertablePageVerification, InsertablePageVerifier, UpdatablePageVerification } from "../../database/types/entity.types";
import { PaginationOptions } from "../../database/pagination/pagination-options";
import { SpaceMemberRepo } from "../../database/repos/space/space-member.repo";
import { PagePermissionRepo } from "../../database/repos/page/page-permission.repo";
export declare class PageVerificationRepo {
    private readonly db;
    private readonly spaceMemberRepo;
    private readonly pagePermissionRepo;
    constructor(db: KyselyDB, spaceMemberRepo: SpaceMemberRepo, pagePermissionRepo: PagePermissionRepo);
    findByPageId(pageId: string, workspaceId: string): Promise<{
        verifiers: {
            name: string;
            email: string;
            avatarUrl: string;
            id: string;
            createdAt: Date;
            userId: string;
        }[];
        type: string;
        data: import("../../database/types/db").JsonValue;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        spaceId: string;
        pageId: string;
        expiresAt: Date;
        mode: string;
        periodAmount: number;
        periodUnit: string;
        verifiedAt: Date;
        verifiedById: string;
        requestedAt: Date;
        requestedById: string;
        rejectedAt: Date;
        rejectedById: string;
        rejectionComment: string;
    }>;
    findById(verificationId: string): Promise<{
        verifiers: {
            name: string;
            email: string;
            avatarUrl: string;
            id: string;
            createdAt: Date;
            userId: string;
        }[];
        type: string;
        data: import("../../database/types/db").JsonValue;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        spaceId: string;
        pageId: string;
        expiresAt: Date;
        mode: string;
        periodAmount: number;
        periodUnit: string;
        verifiedAt: Date;
        verifiedById: string;
        requestedAt: Date;
        requestedById: string;
        rejectedAt: Date;
        rejectedById: string;
        rejectionComment: string;
    }>;
    findAllWithExpiry(): Promise<Array<{
        id: string;
        expiresAt: Date;
    }>>;
    insertVerification(data: InsertablePageVerification, trx?: KyselyTransaction): Promise<{
        type: string;
        data: import("../../database/types/db").JsonValue;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        spaceId: string;
        pageId: string;
        expiresAt: Date;
        mode: string;
        periodAmount: number;
        periodUnit: string;
        verifiedAt: Date;
        verifiedById: string;
        requestedAt: Date;
        requestedById: string;
        rejectedAt: Date;
        rejectedById: string;
        rejectionComment: string;
    }>;
    insertVerifiers(verifiers: InsertablePageVerifier[], trx?: KyselyTransaction): Promise<{
        id: string;
        createdAt: Date;
        userId: string;
        addedById: string;
        pageVerificationId: string;
        isPrimary: boolean;
    }[]>;
    updateVerification(id: string, data: UpdatablePageVerification, trx?: KyselyTransaction): Promise<{
        type: string;
        data: import("../../database/types/db").JsonValue;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        spaceId: string;
        pageId: string;
        expiresAt: Date;
        mode: string;
        periodAmount: number;
        periodUnit: string;
        verifiedAt: Date;
        verifiedById: string;
        requestedAt: Date;
        requestedById: string;
        rejectedAt: Date;
        rejectedById: string;
        rejectionComment: string;
    }>;
    deleteByPageId(pageId: string): Promise<import("kysely").DeleteResult[]>;
    deleteVerifiersByVerificationId(verificationId: string, trx?: KyselyTransaction): Promise<import("kysely").DeleteResult[]>;
    findByWorkspace(userId: string, workspaceId: string, filters: {
        spaceIds?: string[];
        verifierId?: string;
        type?: string;
    }, pagination: PaginationOptions): Promise<{
        items: {
            verifiers: any[];
            type: string;
            id: string;
            createdAt: Date;
            status: string;
            spaceId: string;
            pageId: string;
            expiresAt: Date;
            mode: string;
            periodAmount: number;
            periodUnit: string;
            verifiedAt: Date;
            spaceSlug: string;
            pageTitle: string;
            pageSlugId: string;
            pageIcon: string;
            spaceName: string;
        }[];
        meta: {
            limit: number;
            hasNextPage: boolean;
            hasPrevPage: boolean;
            nextCursor: string | null;
            prevCursor: string | null;
        };
    }>;
}
