import Stripe from 'stripe';
import { KyselyDB, KyselyTransaction } from "../../../database/types/kysely.types";
import { Queue } from 'bullmq';
import { EnvironmentService } from '../../../integrations/environment/environment.service';
export declare class SubscriptionHandlerService {
    private readonly db;
    private billingQueue;
    private environmentService;
    private readonly logger;
    private readonly stripe;
    constructor(db: KyselyDB, billingQueue: Queue, environmentService: EnvironmentService);
    handleSubscriptionCreated(event: Stripe.CustomerSubscriptionCreatedEvent.Data): Promise<void>;
    handleSubscriptionUpdated(event: Stripe.CustomerSubscriptionUpdatedEvent.Data): Promise<void>;
    handleSubscriptionCanceled(event: Stripe.CustomerSubscriptionDeletedEvent.Data): Promise<void>;
    handleCustomerUpdated(event: Stripe.CustomerUpdatedEvent.Data): Promise<void>;
    saveSubscription(eventData: Stripe.CustomerSubscriptionCreatedEvent.Data | Stripe.CustomerSubscriptionUpdatedEvent.Data, workspaceId: string, trx?: KyselyTransaction): Promise<{
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        metadata: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        amount: string;
        billingScheme: string;
        cancelAt: Date;
        cancelAtPeriodEnd: boolean;
        canceledAt: Date;
        currency: string;
        endedAt: Date;
        interval: string;
        periodEndAt: Date;
        periodStartAt: Date;
        planName: string;
        quantity: string;
        stripeItemId: string;
        stripePriceId: string;
        stripeProductId: string;
        stripeSubscriptionId: string;
        tieredFlatAmount: string;
        tieredUnitAmount: string;
        tieredUpTo: string;
    }>;
    private calculateSubscriptionData;
    findByStripeSubId(stripeSubscriptionId: string): Promise<{
        id: string;
        workspaceId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        metadata: import("../../../database/types/db").JsonValue;
        status: string;
        stripeCustomerId: string;
        amount: string;
        billingScheme: string;
        cancelAt: Date;
        cancelAtPeriodEnd: boolean;
        canceledAt: Date;
        currency: string;
        endedAt: Date;
        interval: string;
        periodEndAt: Date;
        periodStartAt: Date;
        planName: string;
        quantity: string;
        stripeItemId: string;
        stripePriceId: string;
        stripeProductId: string;
        stripeSubscriptionId: string;
        tieredFlatAmount: string;
        tieredUnitAmount: string;
        tieredUpTo: string;
    }>;
}
