import { FastifyReply, FastifyRequest } from 'fastify';
import { TokenService } from '../../../core/auth/services/token.service';
import { SessionService } from '../../../core/session/session.service';
import { WorkspaceRepo } from "../../../database/repos/workspace/workspace.repo";
import { SsoService } from "./sso.service";
import { ManageSsoService } from "./manage-sso.service";
import { KyselyDB } from "../../../database/types/kysely.types";
import { UserRepo } from "../../../database/repos/user/user.repo";
import { WorkspaceService } from '../../../core/workspace/services/workspace.service';
import { IAuditService } from '../../../integrations/audit/audit.service';
export declare class GoogleSsoService {
    private readonly tokenService;
    private readonly sessionService;
    private readonly workspaceRepo;
    private readonly ssoService;
    private readonly manageSsoService;
    private readonly userRepo;
    private readonly workspaceService;
    private readonly db;
    private readonly auditService;
    private readonly logger;
    constructor(tokenService: TokenService, sessionService: SessionService, workspaceRepo: WorkspaceRepo, ssoService: SsoService, manageSsoService: ManageSsoService, userRepo: UserRepo, workspaceService: WorkspaceService, db: KyselyDB, auditService: IAuditService);
    handleCallback(req: FastifyRequest, res: FastifyReply): Promise<{
        workspace: {
            hostname: string;
            description: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date;
            auditRetentionDays: number;
            trashRetentionDays: number;
            billingEmail: string;
            customDomain: string;
            defaultRole: string;
            defaultSpaceId: string;
            emailDomains: string[];
            enforceMfa: boolean;
            enforceSso: boolean;
            isScimEnabled: boolean;
            licenseKey: string;
            logo: string;
            name: string;
            plan: string;
            settings: import("../../../database/types/db").JsonValue;
            status: string;
            stripeCustomerId: string;
            trialEndAt: Date;
        };
        authToken: string;
        exchangeToken: string;
    }>;
    handleWorkspaceCreation(req: FastifyRequest): Promise<{
        workspace: {
            hostname: string;
            description: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date;
            auditRetentionDays: number;
            trashRetentionDays: number;
            billingEmail: string;
            customDomain: string;
            defaultRole: string;
            defaultSpaceId: string;
            emailDomains: string[];
            enforceMfa: boolean;
            enforceSso: boolean;
            isScimEnabled: boolean;
            licenseKey: string;
            logo: string;
            name: string;
            plan: string;
            settings: import("../../../database/types/db").JsonValue;
            status: string;
            stripeCustomerId: string;
            trialEndAt: Date;
        };
        authToken: string;
        exchangeToken: string;
    }>;
}
