import { SearchResponseDto } from '../../core/search/dto/search-response.dto';
import { Page } from "../../database/types/entity.types";
import { SearchResponse } from 'typesense/lib/Typesense/Documents';
export declare function transformSearchResults(result: SearchResponse<any>, spaceMap?: Map<string, any>): SearchResponseDto[];
export declare function transformPageToDocument(page: Partial<Page>): {
    id: string;
    slugId: string;
    title: string;
    icon: string;
    textContent: string;
    workspaceId: string;
    spaceId: string;
    creatorId: string;
    contributorIds: string[];
    parentPageId: string;
    createdAt: number;
    updatedAt: number;
    deletedAt: Date;
};
export declare function extractTypesenseError(error: any): any;
