import { TemplateService } from './services/template.service';
import { User, Workspace } from "../../database/types/entity.types";
import { CreateTemplateDto } from './dto/create-template.dto';
import { UpdateTemplateDto } from './dto/update-template.dto';
import { TemplateIdDto } from './dto/template-id.dto';
import { UseTemplateDto } from './dto/use-template.dto';
import { TemplateListDto } from './dto/template-list.dto';
import { PaginationOptions } from "../../database/pagination/pagination-options";
import WorkspaceAbilityFactory from '../../core/casl/abilities/workspace-ability.factory';
import SpaceAbilityFactory from '../../core/casl/abilities/space-ability.factory';
import { SpaceMemberRepo } from "../../database/repos/space/space-member.repo";
import { TemplateRepo } from "../../database/repos/template/template.repo";
export declare class TemplateController {
    private readonly templateService;
    private readonly templateRepo;
    private readonly spaceMemberRepo;
    private readonly workspaceAbility;
    private readonly spaceAbility;
    constructor(templateService: TemplateService, templateRepo: TemplateRepo, spaceMemberRepo: SpaceMemberRepo, workspaceAbility: WorkspaceAbilityFactory, spaceAbility: SpaceAbilityFactory);
    getTemplates(dto: TemplateListDto, pagination: PaginationOptions, user: User, workspace: Workspace): Promise<import("../../database/pagination/cursor-pagination").CursorPaginationResult<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        tsv: string;
        spaceId: string;
        icon: string;
        lastUpdatedById: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
        collaboratorIds: string[];
    } & {
        creator: {
            id: string;
            name: string;
            avatarUrl: string;
        };
    }, undefined>>;
    getTemplate(dto: TemplateIdDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        tsv: string;
        spaceId: string;
        icon: string;
        lastUpdatedById: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
        collaboratorIds: string[];
    }>;
    createTemplate(dto: CreateTemplateDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        tsv: string;
        spaceId: string;
        icon: string;
        lastUpdatedById: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
        collaboratorIds: string[];
    }>;
    updateTemplate(dto: UpdateTemplateDto, user: User, workspace: Workspace): Promise<{
        description: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        tsv: string;
        spaceId: string;
        icon: string;
        lastUpdatedById: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
        collaboratorIds: string[];
    }>;
    deleteTemplate(dto: TemplateIdDto, user: User, workspace: Workspace): Promise<void>;
    useTemplate(dto: UseTemplateDto, user: User, workspace: Workspace): Promise<{
        id: string;
        workspaceId: string;
        creatorId: string;
        title: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        content: import("../../database/types/db").JsonValue;
        tsv: string;
        spaceId: string;
        contributorIds: string[];
        coverPhoto: string;
        deletedById: string;
        icon: string;
        isBase: boolean;
        baseSchemaVersion: number;
        isLocked: boolean;
        lastUpdatedById: string;
        parentPageId: string;
        position: string;
        slugId: string;
        textContent: string;
        ydoc: Buffer<ArrayBufferLike>;
    }>;
    private validateTemplateReadAccess;
    private validateTemplateWriteAccess;
}
