import { CreateSsoProviderDto, SsoProviderIdDto, UpdateSsoProviderDto } from "../dto/sso.dto";
import WorkspaceAbilityFactory from '../../../core/casl/abilities/workspace-ability.factory';
import { PaginationOptions } from "../../../database/pagination/pagination-options";
import { User, Workspace } from "../../../database/types/entity.types";
import { ManageSsoService } from "../services/manage-sso.service";
import { IAuditService } from '../../../integrations/audit/audit.service';
export declare class SsoController {
    private readonly manageSsoService;
    private readonly workspaceAbility;
    private readonly auditService;
    constructor(manageSsoService: ManageSsoService, workspaceAbility: WorkspaceAbilityFactory, auditService: IAuditService);
    getSsoProviders(pagination: PaginationOptions, user: User, workspace: Workspace): Promise<import("../../../database/pagination/cursor-pagination").CursorPaginationResult<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        allowSignup: boolean;
        isEnabled: boolean;
        groupSync: boolean;
        ldapBaseDn: string;
        ldapBindDn: string;
        ldapBindPassword: string;
        ldapTlsCaCert: string;
        ldapTlsEnabled: boolean;
        ldapUrl: string;
        ldapUserAttributes: import("../../../database/types/db").JsonValue;
        ldapUserSearchFilter: string;
        ldapConfig: import("../../../database/types/db").JsonValue;
        oidcClientId: string;
        oidcClientSecret: string;
        oidcIssuer: string;
        samlCertificate: string;
        samlUrl: string;
    }, undefined>>;
    getSsoProvider(dto: SsoProviderIdDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        allowSignup: boolean;
        isEnabled: boolean;
        groupSync: boolean;
        ldapBaseDn: string;
        ldapBindDn: string;
        ldapBindPassword: string;
        ldapTlsCaCert: string;
        ldapTlsEnabled: boolean;
        ldapUrl: string;
        ldapUserAttributes: import("../../../database/types/db").JsonValue;
        ldapUserSearchFilter: string;
        ldapConfig: import("../../../database/types/db").JsonValue;
        oidcClientId: string;
        oidcClientSecret: string;
        oidcIssuer: string;
        samlCertificate: string;
        samlUrl: string;
    }>;
    createSsoProvider(dto: CreateSsoProviderDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        allowSignup: boolean;
        isEnabled: boolean;
        groupSync: boolean;
        ldapBaseDn: string;
        ldapBindDn: string;
        ldapBindPassword: string;
        ldapTlsCaCert: string;
        ldapTlsEnabled: boolean;
        ldapUrl: string;
        ldapUserAttributes: import("../../../database/types/db").JsonValue;
        ldapUserSearchFilter: string;
        ldapConfig: import("../../../database/types/db").JsonValue;
        oidcClientId: string;
        oidcClientSecret: string;
        oidcIssuer: string;
        samlCertificate: string;
        samlUrl: string;
    }>;
    updateSsoProvider(dto: UpdateSsoProviderDto, user: User, workspace: Workspace): Promise<{
        type: string;
        id: string;
        workspaceId: string;
        creatorId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        name: string;
        settings: import("../../../database/types/db").JsonValue;
        allowSignup: boolean;
        isEnabled: boolean;
        groupSync: boolean;
        ldapBaseDn: string;
        ldapBindDn: string;
        ldapBindPassword: string;
        ldapTlsCaCert: string;
        ldapTlsEnabled: boolean;
        ldapUrl: string;
        ldapUserAttributes: import("../../../database/types/db").JsonValue;
        ldapUserSearchFilter: string;
        ldapConfig: import("../../../database/types/db").JsonValue;
        oidcClientId: string;
        oidcClientSecret: string;
        oidcIssuer: string;
        samlCertificate: string;
        samlUrl: string;
    }>;
    deleteSsoProvider(dto: SsoProviderIdDto, user: User, workspace: Workspace): Promise<void>;
    validateAccess(user: User, workspace: Workspace): Promise<void>;
}
